server:
  port: 9599
spring:
  rabbitmq:
    addresses: 127.0.0.1:5672
    username: sa
    password: 123456
    virtual-host: /vvv/sit
  cloud:
    stream:
      bindings:
        testInput:
          destination: exchange-fanout-888
          group: test-queue2
      rabbit:
        bindings:
          testInput.consumer:
            exchangeType: fanout

